config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "public_recipes#index"

  get '/public_recipes', to: 'public_recipes#index', as: 'public_recipes'
  get '/public_recipes/:id', to: 'public_recipes#show', as: 'show_public_recipes'
  
  get '/recipes', to: 'recipes#index', as: 'recipes_index'
  get '/recipes/new', to: 'recipes#new', as: 'recipes_new'
  get '/recipes/:recipe_id', to: 'recipes#show', as: 'recipes_show'
  put '/recipes/:recipe_id', to: 'recipes#update', as: 'recipes_update'
  delete '/recipes/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  post '/recipes/:user_id/recipe', to: "recipes#create", as: 'create_recipe'

 
  get 'recipes/:recipe_id/food_recipes/new', to: 'food_recipes#new', as: 'new_food_recipe'
  get 'recipes/:recipe_id/food_recipes/:food_recipe_id', to: 'food_recipes#edit', as: 'edit_food_recipes'
  put 'recipes/:recipe_id/food_recipes/:food_recipe_id', to: 'food_recipes#update', as: 'update_food_recipes'
  post 'recipes/:recipe_id/food_recipe', to: 'food_recipes#create', as: 'create_food_recipe'
  delete 'recipes/:recipe_id/food_recipe/:food_recipe_id', to: 'food_recipes#destroy', as: 'delete_food_recipe'

  get '/shopping_list', to: 'shopping#index', as: 'shopping_index'
  
  get '/inventories', to: 'inventories#index', as: 'inventories_index'
  get '/inventories/new', to: 'inventories#new', as: 'inventories_new'
  get '/inventories/:inventory_id', to: 'inventories#show', as: 'inventories_show'
  get '/inventories/:inventory_id/foods/new', to: 'inventories#newfood_inventory', as: 'inventories_newfood'
  post '/inventories/:inventory_id/foods/new', to: 'inventories#post_newfood_inventory', as: 'post_inventories_newfood'
  post '/inventories/new', to: 'inventories#create', as: 'inventories_create'
  delete '/inventories/:inventory_id', to: 'inventories#destroy', as: 'inventories_destroy'
  delete '/inventories/:inventory_id/foods/:foods_id', to: 'inventories#destroy_food', as: 'inventories_destroy_foods'


  get '/foods', to: 'foods#index', as: 'foods_index'
  get '/foods/new', to: 'foods#new', as: 'foods_new'
  post '/foods/:user_id', to: 'foods#create', as: 'create_foods_form'
  get '/foods/:id', to: 'foods#show', as: 'foods_show'
  get '/foods/:id/destroy', to: 'foods#destroy', as: 'foods_destroy'


  post '/shopping_list/:recipe_id', to: 'shopping#show', as: 'shopping_show'
  
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  validates :name, presence: { message: 'Name must not be blank!' }
  validates :description, presence: { message: 'Description must not be blank' }

  belongs_to :user
  has_many :inventory_food, dependent: :destroy
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_inventory = Inventory.where(user_id: current_user.id)
  end

  def new
    @inventory = Inventory.new
  end

  def show
    @selected_inventory = Inventory.find(params[:inventory_id])
    @selected_inventory_foods = InventoryFood.where(inventory_id: params[:inventory_id]).includes(:food)
  end

  def create
    @inventory = Inventory.new
    @inventory.name = params[:inventory][:name]
    @inventory.description = params[:inventory][:description]
    @inventory.user_id = current_user.id

    if @inventory.save
      flash[:success] = 'Inventory successfully created.'
      redirect_to inventories_index_path

    else
      p @inventory.errors.full_messages
      flash[:error_title] = @inventory.errors.messages[:name][0]
      flash[:error_comment] = @inventory.errors.messages[:description][0]
      redirect_to inventories_new_path
    end
  end

  def destroy
    @inventory = Inventory.find(params[:inventory_id])
    @inventory.destroy
    flash[:success] = 'Inventory successfully deleted'
    redirect_to inventories_index_path
  end

  def destroy_food
    @food_to_delete = InventoryFood.where(inventory_id: params[:inventory_id], food_id: params[:foods_id]).first
    p @food_to_delete
    if @food_to_delete.destroy

      flash[:success] = 'Food delete from inventory successfully.'
    else
      flash[:error] = 'Opps! Something went wrong'
    end

    redirect_to inventories_show_path(params[:inventory_id])
  end

  def newfood_inventory
    @foods = Food.where(user_id: current_user)
    @inventory_food = InventoryFood.new
    @selected_inventory = Inventory.find(params[:inventory_id])
  end

  def post_newfood_inventory
    @inventory_food = InventoryFood.new

    @inventory_food.quantity = params[:inventory_food][:quantity]
    @inventory_food.inventory_id = params[:inventory_id]
    @inventory_food.food_id = params[:inventory_food][:food_id]

    if @inventory_food.save
      flash[:success] = 'Food added to inventory!'
    else
      p @inventory_food.errors.full_messages
      flash[:error] = 'Food add failed'
    end
    redirect_to inventories_show_path(params[:inventory_id])
  end
end

app/views/inventories/index.html.erb
<body class="page_body">

            <div class="new-inventory-button">
            <%= link_to inventories_new_path, class: "link_style" do %>
              <button class="button-29" role="button">New inventory</button>
              <% end %>
            </div>

        <%= render 'shared/messageflash'%>
            <% if @user_inventory.empty?%>
        <%= render 'shared/nodatacard', :message => "No inventories found."%>
      <% else %>

    <% @user_inventory.each do |inventory| %>
    
        <%= render 'shared/inventorycard', :inventory => inventory%>
    
    <%  end %>
    <%  end %>
    

</body>

app/views/inventories/new.html.erb
<body class="page_body">
    <%= render 'shared/messageflash'%>
      <div class="blog-slider">

<h2 class="blog-slider__title title-center">Add new inventory</h2>

  <%= form_with(model: @inventory, url: inventories_create_path, method: :post, local: true) do |f| %>

<h2 class="background double">
<span>
    <%= f.label :name %><br />
</span>
</h2>

 <div class="session-input-container">
<%= f.text_field :name %>
</div>


<h2 class="background double">
<span>
    <%= f.label :description %><br />
</span>
</h2>

 <div class="session-input-container">
<%= f.text_field :description %>
</div>


<div class="links-align">

<div class="actions button_margin">
    <%= f.submit "Add new", class:"button-29" %>
  </div>
  </div>
<%end%>


</div>
</body>

app/views/inventories/newfood_inventory.html.erb
<body class="page_body">
        <%= render 'shared/messageflash'%>

              <div class="blog-slider">
              <h2 class="blog-slider__title title-center">Add an food to <%= @selected_inventory.name %></h2>

  <%= form_with(model: @inventory_food, url: post_inventories_newfood_path(@selected_inventory.id), method: :post, local: true) do |f| %>

    <h2 class="background double">
<span>
      <%= f.label :foods_id, 'Food' %><br>
</span>
</h2>

 <div class="food-input-align">
 <% foods_array = @foods.map { |f| [f.name, f.id] } %>
      <div class="dflex-row select">
      <%= f.select(:food_id, options_for_select(foods_array), class: "select-tag") %>
      </div>
      </div>


<h2 class="background double">
<span>
      <%= f.label :quantity %><br>
</span>
</h2>

 <div class="session-input-container">
      <%= f.number_field :quantity, min: 0 %>
</div>

   
<div class="links-align">

<div class="actions button_margin">
      <%= f.submit 'Add ingredient', class:"button-29" %>
    </div>
    </div>
  <% end %>
</div>
</body>

app/views/inventories/show.html.erb
<body class="page_body">


    <div class="title-center">
    <%= link_to inventories_newfood_path(@selected_inventory.id), class: "link_style" do %>
            <button class="button-29" role="button">Add new food</button>
    <%end%>
    </div>

    <%= render 'shared/messageflash'%>


    <% if @selected_inventory_foods.empty?%>
        <%= render 'shared/nodatacard', :message => "The inventory #{@selected_inventory.name} is Empty"%>
      <% else %>

      <div class="blog-slider new-shadow new-height">

<div class="recipe-info-container">
    <div class="recipe-title-container">
        <h2><%= @selected_inventory.name %></h2>

            <%= render 'shared/inventoryfoodstable', :foods => @selected_inventory_foods, :inventory => @selected_inventory%>





    </div>
    </div>
    </div>

   
    <%  end %>


</body>