config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "public_recipes#index"

  get '/public_recipes', to: 'public_recipes#index', as: 'public_recipes'
  get '/public_recipes/:id', to: 'public_recipes#show', as: 'show_public_recipes'
  
  get '/recipes', to: 'recipes#index', as: 'recipes_index'
  get '/recipes/new', to: 'recipes#new', as: 'recipes_new'
  get '/recipes/:recipe_id', to: 'recipes#show', as: 'recipes_show'
  put '/recipes/:recipe_id', to: 'recipes#update', as: 'recipes_update'
  delete '/recipes/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  post '/recipes/:user_id/recipe', to: "recipes#create", as: 'create_recipe'

 
  get 'recipes/:recipe_id/food_recipes/new', to: 'food_recipes#new', as: 'new_food_recipe'
  get 'recipes/:recipe_id/food_recipes/:food_recipe_id', to: 'food_recipes#edit', as: 'edit_food_recipes'
  put 'recipes/:recipe_id/food_recipes/:food_recipe_id', to: 'food_recipes#update', as: 'update_food_recipes'
  post 'recipes/:recipe_id/food_recipe', to: 'food_recipes#create', as: 'create_food_recipe'
  delete 'recipes/:recipe_id/food_recipe/:food_recipe_id', to: 'food_recipes#destroy', as: 'delete_food_recipe'

  get '/shopping_list', to: 'shopping#index', as: 'shopping_index'
  
  get '/inventories', to: 'inventories#index', as: 'inventories_index'
  get '/inventories/new', to: 'inventories#new', as: 'inventories_new'
  get '/inventories/:inventory_id', to: 'inventories#show', as: 'inventories_show'
  get '/inventories/:inventory_id/foods/new', to: 'inventories#newfood_inventory', as: 'inventories_newfood'
  post '/inventories/:inventory_id/foods/new', to: 'inventories#post_newfood_inventory', as: 'post_inventories_newfood'
  post '/inventories/new', to: 'inventories#create', as: 'inventories_create'
  delete '/inventories/:inventory_id', to: 'inventories#destroy', as: 'inventories_destroy'
  delete '/inventories/:inventory_id/foods/:foods_id', to: 'inventories#destroy_food', as: 'inventories_destroy_foods'


  get '/foods', to: 'foods#index', as: 'foods_index'
  get '/foods/new', to: 'foods#new', as: 'foods_new'
  post '/foods/:user_id', to: 'foods#create', as: 'create_foods_form'
  get '/foods/:id', to: 'foods#show', as: 'foods_show'
  get '/foods/:id/destroy', to: 'foods#destroy', as: 'foods_destroy'


  post '/shopping_list/:recipe_id', to: 'shopping#show', as: 'shopping_show'
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: { message: 'Name must not be blank!' }
  validates :preparation_time, presence: { message: 'Preparation time must not be blank!' }
  validates :cooking_time, presence: { message: 'Cooking time must not be blank!' }
  validates :description, presence: { message: 'Description must not be blank!' }

  belongs_to :user
  has_many :food_recipes, dependent: :destroy

  def self.count(id)
    FoodRecipe.where(recipe_id: id).count
  end

  def self.total(id)
    foods = FoodRecipe.where(recipe_id: id).includes(:food)
    total = 0
    unless foods.empty?
      foods.each do |food|
        total += (food.quantity * food.food.price)
      end
    end
    total
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:recipe_id])

    if !user_signed_in? && (@recipe.public == false)
      flash[:message] = 'You need to sign in or sign up before continuing.'
      redirect_to root_path
    end

    if user_signed_in? && ((@recipe.user_id != current_user.id) && @recipe.public == false)
      flash[:message] = 'You have no access to this post.'
      redirect_to root_path
    end

    @inventory = Inventory.where(user_id: @recipe.user_id)
    @food_recipes = FoodRecipe.where(recipe_id: @recipe.id).includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new
    @recipe.name = params[:recipe][:name]
    @recipe.preparation_time = params[:recipe][:preparation_time]
    @recipe.cooking_time = params[:recipe][:cooking_time]
    @recipe.description = params[:recipe][:description]
    @recipe.user_id = params[:user_id]

    if @recipe.save
      flash[:success] = 'Recipe saved successfully'
      redirect_to recipes_index_path
    else
      flash[:error] = 'Recipe save failed'
    end
  end

  def update
    recipe = Recipe.find(params[:recipe_id])
    case recipe.public
    when false
      recipe.public = true
      recipe.save
      redirect_to recipes_show_path(recipe.id)
    when true
      recipe.public = false
      recipe.save
      redirect_to recipes_show_path(recipe.id)
    end
  end

  def destroy
    recipe = Recipe.find(params[:recipe_id])
    recipe.destroy
    if recipe.destroy
      flash[:success] = 'Recipe deleted'
      redirect_to recipes_index_path
    else
      flash[:error] = 'Recipe delete failed'
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<body class="page_body">

  <%= link_to recipes_new_path, class: "link_style title-center" do %>
              <button class="button-29" role="button">Create new recipe</button>
              <% end %>
            </div>

  <%= render 'shared/messageflash'%>


<% if @recipes.empty?%>
        <%= render 'shared/nodatacard', :message => "No recipes found."%>
      <% else %>

  <% @recipes.each do |recipe|%>
    <%= link_to recipes_show_path(recipe.id),  class: "link_style" do %>
  <div class="blog-slider new-shadow new-height link-style recipe-info-container">
  <div class="recipe-title-container">
          <h2><%= recipe.name %></h2>
          <%= button_to delete_recipe_path(recipe.id), method: :delete, class: "delete-button-active" do%>
            <ion-icon name="trash-outline"></ion-icon>
          <% end%>
        </div>
        <div>
          <p><%= recipe.description %></p>
        </div>
  </div>
</div>
    <% end %>
  <% end %>
  <% end %>
</body>

app/views/recipes/new.html.erb
<body class="page_body">
  <%= render 'shared/messageflash'%>

      <div class="blog-slider">

<h2 class="blog-slider__title title-center">Add a new recipe</h2>

    <%= form_with model: @recipe, url: create_recipe_path(current_user), method: :post do |f| %>
      
      <h2 class="background double">
<span>
        <%= f.label :name, class: "recipe-label" %><br>
</span>
</h2>

 <div class="session-input-container">
        <%= f.text_field :name, class: "recipe-text" %>
</div>


      <h2 class="background double">
<span>
        <%= f.label :description %><br>
</span>
</h2>

 <div class="session-input-container">
        <%= f.text_area :description, width: "100%" %>
</div>
      
      <h2 class="background double">
<span>
        <%= f.label :preparation_time %><br>
</span>
</h2>

 <div class="session-input-container">
        <%= f.text_field :preparation_time, placeholder: "Example: 1 hour, minute etc.." %>
</div>
     
      <h2 class="background double">
<span>
        <%= f.label :cooking_time %><br>
</span>
</h2>

 <div class="session-input-container">
        <%= f.text_field :cooking_time, placeholder: "Example: 1 hour, minute etc.."  %>
</div>
      
      
     
     
     
      <div class="links-align">

      <div class="actions button_margin">
        <%= f.submit "Add recipe", class: "button-29" %>
      </div>
      </div>
    <% end %>
</div>
</body>

app/views/recipes/show.html.erb
<body class="page_body">

<%= render "shared/messageflash" %>

<div class="blog-slider">

<h2 class="blog-slider__title title-center"><%= @recipe.name %></h2>

  <div class="recipe-info">
    <div class="preparation-div">
      <span class="recipe-description">Preparation time: <%= @recipe.preparation_time %></span>
      <span class="recipe-description">Cooking time: <%= @recipe.cooking_time %></span>
    </div>
    <div>
    <% if can? :manage, @recipe %>
      <%= form_with model: @recipe, url: recipes_update_path(params[:recipe_id]), method: :put do |f| %>
        <div class="custom-control custom-switch">
          <%= f.check_box :public, class: "custom-control-input", id: "flexSwitchCheckDefault", onchange: "this.form.submit();" %>
          <%= f.label :public, ' ', class: "custom-control-label", for: "flexSwitchCheckDefault" %>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>

  <hr class="hr-class"/>
      <h3 class="title-center recipe-description-label">Description</h3>
      <p class="title-center">Steps go here: <%= @recipe.description %></p>
  
  <% if can? :manage, @recipe %>
    <div class="show-recipe-btns">
    
  <% if !@food_recipes.empty?  %>
      <button onclick="toggleModal()" class="button-29 generate-shopping-button">Generate shopping list</button>
  <% end  %>
      <%= link_to new_food_recipe_path(params[:recipe_id]), class: "link_style" do%>
      <button class="button-29 add-food-button">Add ingredient</button>
      <%end%>
    </div>
  <% end %>


<% if @food_recipes.empty?%>
        <%= render 'shared/nodatacard', :message => "No food found."%>
      <% else %>

  
  <div class="recipe-table-container">
    <table class="table table-bordered table-dark">
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <% if can? :manage, @recipe %>
        <th>Actions</th>
        <% end %>
      </tr>
      <% @food_recipes.each do |food_recipe| %>
        <tr>
          <td><%= food_recipe.food.name %></td>
          <td><%= food_recipe.quantity %> <%= food_recipe.food.measurement_unit %></td>
          <td><%= (food_recipe.food.price * food_recipe.quantity).round(2) %></td>
          <% if can? :manage, @recipe %>
          <td class="recipe-action-buttons">
          <%= link_to edit_food_recipes_path(params[:recipe_id], food_recipe.id), method: :put, class: "edit-button-active link_style"  do %> 
          <ion-icon name="create-outline"></ion-icon>
          <% end %> 
          
          <%= button_to delete_food_recipe_path(params[:recipe_id], food_recipe.id), method: :delete, class: "delete-button-active" do%>
            <ion-icon name="trash-outline"></ion-icon>
          <% end%>
          
          </td>
          
          <% end %>
        </tr>
      <% end%>
    </table>
  </div>
      <% end %>
</div>

  <%= render "shared/shoppingmodal" %>

</body>