config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "public_recipes#index"

  get '/public_recipes', to: 'public_recipes#index', as: 'public_recipes'
  get '/public_recipes/:id', to: 'public_recipes#show', as: 'show_public_recipes'
  
  get '/recipes', to: 'recipes#index', as: 'recipes_index'
  get '/recipes/new', to: 'recipes#new', as: 'recipes_new'
  get '/recipes/:recipe_id', to: 'recipes#show', as: 'recipes_show'
  put '/recipes/:recipe_id', to: 'recipes#update', as: 'recipes_update'
  delete '/recipes/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  post '/recipes/:user_id/recipe', to: "recipes#create", as: 'create_recipe'

 
  get 'recipes/:recipe_id/food_recipes/new', to: 'food_recipes#new', as: 'new_food_recipe'
  get 'recipes/:recipe_id/food_recipes/:food_recipe_id', to: 'food_recipes#edit', as: 'edit_food_recipes'
  put 'recipes/:recipe_id/food_recipes/:food_recipe_id', to: 'food_recipes#update', as: 'update_food_recipes'
  post 'recipes/:recipe_id/food_recipe', to: 'food_recipes#create', as: 'create_food_recipe'
  delete 'recipes/:recipe_id/food_recipe/:food_recipe_id', to: 'food_recipes#destroy', as: 'delete_food_recipe'

  get '/shopping_list', to: 'shopping#index', as: 'shopping_index'
  
  get '/inventories', to: 'inventories#index', as: 'inventories_index'
  get '/inventories/new', to: 'inventories#new', as: 'inventories_new'
  get '/inventories/:inventory_id', to: 'inventories#show', as: 'inventories_show'
  get '/inventories/:inventory_id/foods/new', to: 'inventories#newfood_inventory', as: 'inventories_newfood'
  post '/inventories/:inventory_id/foods/new', to: 'inventories#post_newfood_inventory', as: 'post_inventories_newfood'
  post '/inventories/new', to: 'inventories#create', as: 'inventories_create'
  delete '/inventories/:inventory_id', to: 'inventories#destroy', as: 'inventories_destroy'
  delete '/inventories/:inventory_id/foods/:foods_id', to: 'inventories#destroy_food', as: 'inventories_destroy_foods'


  get '/foods', to: 'foods#index', as: 'foods_index'
  get '/foods/new', to: 'foods#new', as: 'foods_new'
  post '/foods/:user_id', to: 'foods#create', as: 'create_foods_form'
  get '/foods/:id', to: 'foods#show', as: 'foods_show'
  get '/foods/:id/destroy', to: 'foods#destroy', as: 'foods_destroy'


  post '/shopping_list/:recipe_id', to: 'shopping#show', as: 'shopping_show'
  
end

app/views/shared/_inventorycard.html.erb
     <%= link_to inventories_show_path(inventory.id), class: "link_style center_button" do %>
    <div class="blog-slider new-shadow new-height">

<div class="recipe-info-container">
    <div class="recipe-title-container">
    <h2><%= inventory.name %></h2>
                     <%= button_to "Delete", inventories_destroy_path(inventory.id), method: :delete, class: "button-29 delete_button_style" %>

    </div>
    <div class="recipe-description-container">
    <span class="recipe-description">
    <%= inventory.description %>
    </span>
    </div>
    </div>
    </div>

         <% end %>

app/views/shared/_inventoryfoodstable.html.erb
<table class="table table-bordered table-dark">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Food</th>
        <th scope="col">Unit</th>
        <th scope="col">Action</th>
        </tr>
    </thead>
  <tbody>
  <% foods.each do |food|%>
    <tr>
      <th scope="row"><%= food.food.id%></th>
      <td><%=food.food.name%></td>
      <td><%= food.quantity%> <%= food.food.measurement_unit%></td>
      <td><%= button_to inventories_destroy_foods_path(inventory.id, food.food_id), method: :delete, class: "delete-button-active" do %>
                <ion-icon name="trash-outline"></ion-icon>
      <% end %>
      </td>
    </tr>
  </tbody>
    <%end%>
</table>

app/views/shared/_menu.html.erb
 <div class="mobileMenuCover" id="mobileMenuCover">
      <div class="firstContainer">
        <span id="closeButton" onClick="closeMenu()" class="closeButton">X</span>
      </div>
      <div class="mobileMenu">
        <ul>
         <% if (current_page?(root_path) || current_page?(public_recipes_path)) == false %>
               

          <%= render 'shared/menuitem', :link => "/", :name => "Home" %>

              <% end %>


            <% if user_signed_in? %>
         <%= render 'shared/menuitem', :link => "/recipes", :name => "My Recipes" %>
         <%= render 'shared/menuitem', :link => "/inventories", :name => "My Inventories" %>
         <%= render 'shared/menuitem', :link => "/foods", :name => "My Foods" %>


          <li class="mobileMenuItems">
            <a href="#portfolio" class="mobileMenuItems-a">
              <%= form_with url: '/users/sign_out', method: :delete do |f| %>
                <%= f.submit "Log out", class: "optionMenu"%>
              <% end %>
            </a>
          </li>

        



                      <% else %>

         <%= render 'shared/menuitem', :link => "/users/sign_up", :name => "Sign Up" %>
         <%= render 'shared/menuitem', :link => "/users/sign_in", :name => "Sign In" %>

         
                      <% end %>
        </ul>
      </div>
    </div>

 

app/views/shared/_menuitem.html.erb
 <li class="mobileMenuItems">
            <a href="#contact" class="mobileMenuItems-a">
            <%= link_to link do %>

      
<button class="optionMenu" role="button">              <%= name %></button>
              <%end%>
            </a>
          </li>

app/views/shared/_messageflash.html.erb
 <% flash.each do |message_type, message| %>
    <% if message_type == "error" %>
            <h2 class="flashMessage error_color"><%= message %></h2>
    <% else %>
            <h2 class="flashMessage white_color"><%= message %></h2>
    <% end %>
  
<% end %>

app/views/shared/_nodatacard.html.erb
    <div class="blog-slider new-shadow new-height">

<div class="recipe-info-container">
    <div class="recipe-title-container">
    <h2><%= message %></h2>

    </div>
    
    </div>
    </div>

app/views/shared/_sessionbutton.html.erb
<div class="session_buttons">
<% if user_signed_in? %>

<%= form_with url: '/users/sign_out', method: :delete do |f| %>
    <%= f.submit "Log out", class: 'button-29' %>
  <% end %>
    
<% else %>


<%= link_to "/users/sign_up", class: "link_style center_button" do %>

      
<button class="button-29" role="button">Sign Up</button>
              <%end%>
<%= link_to "/users/sign_in", class: "link_style center_button" do %>

      
<button class="button-29" role="button">Sign In</button>
              <%end%>


<% end %>
</div>

app/views/shared/_shoppinglist.html.erb
<table class="table table-bordered table-dark">
    <thead>
        <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        </tr>
    </thead>
  <tbody>
  <% foods.each do |food|%>
    <tr>
      <td><%=food[:food_name]%></td>
      <td><%= food[:missing_quantity]%></td>
      <td><%= food[:price_to_pay]%></td>
      
    </tr>
  </tbody>
    <%end%>
</table>

app/views/shared/_shoppingmodal.html.erb
<div class="projectDetailsModal gray" id="modal">
          <%= form_with url: shopping_show_path(params[:recipe_id]), class: "modal-form" do |f| %>
    <div class="blog-slider new-height">
          <h2 class="title-center">Generating Shopping List </h2>
          <h5 class="modal-choose-inventory">Choose an inventory to use </h5>
      <% inventory_array = @inventory.map { |f| [f.name, f.id] } %>
      <div class="recipe-action-buttons">
      <div class="dflex-row select ">

      <%= f.select(:inventory_id, options_for_select(inventory_array), class: "select-tag") %>
      </div>
    
    <div class="modal-buttons">
      <%= f.submit 'Create shopping list', class: "button-29" %>
      <a class="button-29 delete_button_style link_style white_color"  onclick="toggleModal()" >Cancel</a>
    </div>
      </div>
    </div>
  <% end %>
</div>