config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "public_recipes#index"

  get '/public_recipes', to: 'public_recipes#index', as: 'public_recipes'
  get '/public_recipes/:id', to: 'public_recipes#show', as: 'show_public_recipes'
  
  get '/recipes', to: 'recipes#index', as: 'recipes_index'
  get '/recipes/new', to: 'recipes#new', as: 'recipes_new'
  get '/recipes/:recipe_id', to: 'recipes#show', as: 'recipes_show'
  put '/recipes/:recipe_id', to: 'recipes#update', as: 'recipes_update'
  delete '/recipes/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  post '/recipes/:user_id/recipe', to: "recipes#create", as: 'create_recipe'

 
  get 'recipes/:recipe_id/food_recipes/new', to: 'food_recipes#new', as: 'new_food_recipe'
  get 'recipes/:recipe_id/food_recipes/:food_recipe_id', to: 'food_recipes#edit', as: 'edit_food_recipes'
  put 'recipes/:recipe_id/food_recipes/:food_recipe_id', to: 'food_recipes#update', as: 'update_food_recipes'
  post 'recipes/:recipe_id/food_recipe', to: 'food_recipes#create', as: 'create_food_recipe'
  delete 'recipes/:recipe_id/food_recipe/:food_recipe_id', to: 'food_recipes#destroy', as: 'delete_food_recipe'

  get '/shopping_list', to: 'shopping#index', as: 'shopping_index'
  
  get '/inventories', to: 'inventories#index', as: 'inventories_index'
  get '/inventories/new', to: 'inventories#new', as: 'inventories_new'
  get '/inventories/:inventory_id', to: 'inventories#show', as: 'inventories_show'
  get '/inventories/:inventory_id/foods/new', to: 'inventories#newfood_inventory', as: 'inventories_newfood'
  post '/inventories/:inventory_id/foods/new', to: 'inventories#post_newfood_inventory', as: 'post_inventories_newfood'
  post '/inventories/new', to: 'inventories#create', as: 'inventories_create'
  delete '/inventories/:inventory_id', to: 'inventories#destroy', as: 'inventories_destroy'
  delete '/inventories/:inventory_id/foods/:foods_id', to: 'inventories#destroy_food', as: 'inventories_destroy_foods'


  get '/foods', to: 'foods#index', as: 'foods_index'
  get '/foods/new', to: 'foods#new', as: 'foods_new'
  post '/foods/:user_id', to: 'foods#create', as: 'create_foods_form'
  get '/foods/:id', to: 'foods#show', as: 'foods_show'
  get '/foods/:id/destroy', to: 'foods#destroy', as: 'foods_destroy'


  post '/shopping_list/:recipe_id', to: 'shopping#show', as: 'shopping_show'
  
end

app/models/food_recipe.rb
class FoodRecipe < ApplicationRecord
  validates :quantity,
            numericality: { message: 'Quantity greater or equal than 1', only_integer: true,
                            greater_than_or_equal_to: 1 }

  belongs_to :recipe
  belongs_to :food
end

app/controllers/food_recipes_controller.rb
class FoodRecipesController < ApplicationController
  before_action :authenticate_user!

  def new
    @foods = Food.where(user_id: current_user)
    @food_recipe = FoodRecipe.new
  end

  def create
    @food_recipe = FoodRecipe.new
    @food_recipe.quantity = params[:quantity]
    @food_recipe.recipe_id = params[:recipe_id]
    @food_recipe.food_id = params[:food_id]
    if @food_recipe.save
      flash[:success] = 'Ingredient added to recipe'
    else
      flash[:error] = 'Ingredient add failed'
    end
    redirect_to recipes_show_path(params[:recipe_id])
  end

  def destroy
    food_recipe = FoodRecipe.find(params[:food_recipe_id])
    food_recipe.destroy
    if food_recipe.destroy
      flash[:success] = 'Ingredient deleted'
    else
      flash[:error] = 'Failed to delete ingredient'
    end
    redirect_to recipes_show_path(params[:recipe_id])
  end

  def edit
    food_recipe = FoodRecipe.find(params[:food_recipe_id])
    @food = Food.find(food_recipe.food_id)
  end

  def update
    @food_recipe = FoodRecipe.find(params[:food_recipe_id])
    new_quantity = params[:quantity]
    @food_recipe.quantity = new_quantity
    @food_recipe.save
    if @food_recipe.save
      flash[:success] = 'Ingredient updated'
    else
      flash[:error] = 'Ingredient updated failed'
    end
    redirect_to recipes_show_path(params[:recipe_id])
  end
end

app/views/food_recipes/edit.html.erb
<body class="page_body">
<div class="blog-slider">
    <h2 class="blog-slider__title title-center">Update Quantity of "<%= @food.name%>"</h2>
  <%= form_with model: @food_recipe, url: update_food_recipes_path(params[:recipe_id], params[:food_recipe_id]), method: :put do |f| %>
  

<h2 class="background double">
<span>
      <%= f.label :quantity %><br>
</span>
</h2>

 <div class="session-input-container">
      <%= f.number_field :quantity, min: 0, placeholder: "Insert quantity" %>
</div>



    <div class="links-align">
  <div class="actions button_margin">
      <%= f.submit 'Update', class: "button-29" %>
    </div>
    </div>
  <% end %>
</div>
</body>

app/views/food_recipes/new.html.erb
<body class="page_body">
<div class="blog-slider">
  <% unless @foods.empty? %>
    <h2 class="blog-slider__title title-center">Add an ingredient</h2>
    <%= form_with url: create_food_recipe_path(params[:recipe_id]), method: :post do |f| %>
      
      <h2 class="background double">
<span>
        <%= f.label :foods_id, 'Food' %><br>
</span>
</h2>

 <div class="session-input-container">
        <% foods_array = @foods.map { |f| [f.name, f.id] } %>
         <div class="dflex-row select">
        <%= f.select(:food_id, options_for_select(foods_array), class: "select-tag") %>
</div>

</div>




<h2 class="background double">
<span>
        <%= f.label :quantity %><br>
</span>
</h2>

 <div class="session-input-container">
        <%= f.number_field :quantity, min: 0, placeholder: "Select quantity" %>
</div>
      
      
<div class="links-align">
  <div class="actions button_margin">
          <%= f.submit 'Add ingredient', class: "button-29" %>
      </div>
      </div>
      </div>
    <% end %>
  <% else %>
  
    <h2 class="blog-slider__title title-center">Currently you don't have any food to add ingredients. Please create some food first</h2>
    <%= link_to foods_new_path, class: "link_style recipes-button-align" do %>
      <button class="button-29" >Create Food!</button>
    <% end %>
  <% end %>
</div>

</body>